language: go

os:
  - linux
  - osx

go:
  - "1.x"

matrix:
  include:
    - os: windows
      install:
        - choco install openjdk
        - refreshenv

script:
  - javac -version
  - go test -v ./...
