language: go

os:
  - linux
  - osx

go:
  - "1.x"

matrix:
  include:
    - os: windows
      install:
        - choco install openjdk
        - export PATH=$PATH:"/c/Program Files/OpenJDK/jdk-11.0.1/bin"

script:
  - javac -version
  - go test -v ./...
